"""Constants for ANP Proxy."""

# Default configuration values
DEFAULT_HTTP_PORT = 8080
DEFAULT_WSS_PORT = 8765
DEFAULT_CHUNK_SIZE = 64 * 1024  # 64KB
DEFAULT_MAX_CONNECTIONS = 100
DEFAULT_TIMEOUT_SECONDS = 30.0
DEFAULT_KEEPALIVE_INTERVAL = 30.0
DEFAULT_PING_INTERVAL = 10.0

# Protocol constants
ANPX_MAGIC = b"ANPX"
ANPX_VERSION = 0x01
ANPX_HEADER_SIZE = 24

# Limits
MAX_MESSAGE_SIZE = 10 * 1024 * 1024  # 10MB
MAX_CHUNK_SIZE = 1024 * 1024  # 1MB
MAX_PENDING_CHUNKS = 1000
MAX_REQUEST_ID_LENGTH = 100

# Timeouts
DEFAULT_CHUNK_TIMEOUT = 60.0  # seconds
DEFAULT_REQUEST_TIMEOUT = 300.0  # 5 minutes
DEFAULT_RECONNECT_DELAY = 5.0  # seconds
DEFAULT_MAX_RECONNECT_ATTEMPTS = 10

# Security
DEFAULT_AUTH_TIMEOUT = 30.0
DEFAULT_TOKEN_EXPIRY = 3600  # 1 hour

# Logging
LOG_FORMAT = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
LOG_DATE_FORMAT = "%Y-%m-%d %H:%M:%S"
